trigger:
 branches:
   include:
     - main  # Replace 'main' with your main branch name
 
variables:
 azureSubscription:'<Azure subscription name>'
 azureResourceGroup:'<Azure resource group name>'
 appName: '<Azure Web App name>'
 pythonVersion:'<Python version>'  # e.g., 3.8
 nodeVersion:'<Node.js version>'    # e.g., 14.x
 
stages:
-stage: Build
 displayName:'Build and Package'
 jobs:
 - job: Build_React
   displayName:'Build React App'
   pool:
     vmImage: 'ubuntu-latest'
   steps:
   - task: NodeTool@0
     inputs:
       versionSpec:'$(nodeVersion)'
     displayName:'Install Node.js'
 
   - script: |
       npm install
       npm run build
     displayName:'Build React Application'
 
   - task: ArchiveFiles@2
     displayName:'Archive Build Artifacts'
     inputs:
       rootFolderOrFile:'$(Build.SourcesDirectory)/build'
       includeRootFolder:false
       archiveType:'zip'
       archiveFile:'$(Build.ArtifactStagingDirectory)/react-app.zip'
       replaceExistingArchive:true
 
 - job: Build_Python
   displayName:'Build Python App'
   pool:
     vmImage: 'ubuntu-latest'
   steps:
   - task: UsePythonVersion@0
     inputs:
       versionSpec:'$(pythonVersion)'
       addToPath: true
     displayName:'Use Python $(pythonVersion)'
 
   - script: |
       python -m pip install --upgrade pip
       pip install -r requirements.txt
     displayName:'Install Python dependencies'
 
   - task: ArchiveFiles@2
     displayName:'Archive Python App'
     inputs:
       rootFolderOrFile:'$(Build.SourcesDirectory)'
       includeRootFolder:false
       archiveType:'zip'
       archiveFile:'$(Build.ArtifactStagingDirectory)/python-app.zip'
       replaceExistingArchive:true
 
-stage: Deploy
 displayName:'Deploy to Azure Web App'
 dependsOn: Build
 jobs:
 - job: Deploy
   displayName:'Deploy to Azure Web App'
   pool:
     vmImage: 'ubuntu-latest'
   steps:
   - task: AzureWebApp@1
     displayName:'Azure Web App Deploy'
     inputs:
       azureSubscription:$(azureSubscription)
       appName: $(appName)
       package: '$(Pipeline.Workspace)/<path-to-your-zip-file>'
       enableCustomDeployment:true
       deploymentMethod:'zipDeploy'
