name: Build and Deploy to Production
 
on:
  push:
    branches:
      - main
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21.1.0'
 
    - name: Install frontend dependencies
      run: npm install
      working-directory: frontend
 
    - name: Build frontend
      run: npm run build
      working-directory: frontend
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Change this to your Python version
 
    - name: Install backend dependencies
      run: pip install -r requirements.txt
      # working-directory: backend  # Change this to your backend directory
 
    - name: Start Gunicorn server
      run: |
        gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app -b 0.0.0.0:8000 --daemon

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: platformconsole-test1
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9BC0EABC93DF4E4C91F5A1AF122F2FC5 }}
